en:
  locale: en-us
  title: Zhuheng Zan

zh:
  locale: zh-Hans
  title: Zhuheng Zan (ZH)
  params:
    description: Chinese version of Zhuheng Zan profile.
  menu:
    main:
      - name: Home (ZH)
        url: /
        weight: 10
      - name: Experience (ZH)
        url: experience/
        weight: 20